var fileList = [
    { value: '00001', text: '金融市場常識與職業道德', category: '其他' },
    { value: '00002', text: '財產保險業務員資格測驗練習題(未完成)', category: '其他' },
    { value: '00003', text: '職業安全衛生業務主管', category: '其他' },
    { value: '00004', text: '有機溶劑', category: '其他' },
    { value: '01033', text: '第33期', category: '銀行內部控制與內部稽核測驗' },
    { value: '01032', text: '第32期', category: '銀行內部控制與內部稽核測驗' },
    { value: '01031', text: '第31期', category: '銀行內部控制與內部稽核測驗' },
    { value: '01030', text: '第30期', category: '銀行內部控制與內部稽核測驗' },
    { value: '01029', text: '第29期', category: '銀行內部控制與內部稽核測驗' },
    { value: '01028', text: '第28期', category: '銀行內部控制與內部稽核測驗' },
    { value: '01027', text: '第27期', category: '銀行內部控制與內部稽核測驗' },
    { value: '01026', text: '第26期', category: '銀行內部控制與內部稽核測驗' },
    { value: '02025', text: '第25期', category: '初階外匯人員專業能力測驗' },
    { value: '02024', text: '第24期', category: '初階外匯人員專業能力測驗' },
    { value: '03007', text: '第7屆', category: '風險管理基本能力測驗' },
    { value: '03006', text: '第6屆', category: '風險管理基本能力測驗' },
    { value: '03005', text: '第5屆', category: '風險管理基本能力測驗' },
    { value: '03004', text: '第4屆', category: '風險管理基本能力測驗' },
    { value: '03003', text: '第3屆', category: '風險管理基本能力測驗' },
    { value: '03002', text: '第2屆', category: '風險管理基本能力測驗' },
    { value: '03001', text: '第1屆', category: '風險管理基本能力測驗' },
    { value: '04001', text: '網路通訊專業人員', category: 'ITE資訊專業人員鑑定' },
    { value: '05001', text: '永續發展基礎能力測驗題庫', category: '永續發展' }
]
